### ISSUE TITLE
clustering of functtion pic

### ISSUE THREAD

**Issue by Akshatau** [P-Division-2018-2019/Team-7#4]
![new doc 2019-02-20 19 45 23_1 1](https://user-images.githubusercontent.com/46949702/53098603-050b7600-354a-11e9-8b1f-4386b69ad376.jpg)

**Comment by Nandinisg** [comment]
![flute assembly](https://user-images.githubusercontent.com/46949745/57274350-9f467900-70b8-11e9-8416-319223cd421b.png)
