### ISSUE TITLE
component hierarchy

### ISSUE THREAD

**Issue by Akshatau** [P-Division-2018-2019/Team-7#5]
![new doc 2019-02-20 19 45 23_2 1](https://user-images.githubusercontent.com/46949702/53100056-186c1080-354d-11e9-86aa-e08dc2ceef9d.jpg)

**Comment by pradeep1999** [comment]
![GitpodGif](https://user-images.githubusercontent.com/46949704/54083551-de6f7c80-434a-11e9-8366-da0b31577493.gif)

![walkthough_step_1](https://user-images.githubusercontent.com/46949704/54083561-f8a95a80-434a-11e9-9ec4-55c7e7c09566.png)

**Comment by Nandinisg** [comment]
(https://user-images.githubusercontent.com/46949745/57319132-87eba800-7119-11e9-95f8-82f5bb7aae4e.png)

**Comment by Nandinisg** [comment]
![BILL](https://user-images.githubusercontent.com/46949745/57319195-abaeee00-7119-11e9-980b-a9e6c1f3a1d8.png)
